In [18]:
import pandas as pd
import numpy as np

In [19]:
df_quicksight = pd.read_csv("data/concatenated_df_2.csv")
df_streamlit = pd.read_csv("data/Conversion_rate_user_info.csv")


df_quicksight[ 'EventDateTime_soft' ] = pd.to_datetime(df_quicksight[ 'EventDateTime_soft'], format="%Y-%m-%dT%H:%M:%S%z")

df_streamlit[ 'EventDateTime_soft' ] = pd.to_datetime(df_streamlit[ 'EventDateTime_soft'], format="%Y-%m-%dT%H:%M:%S%z")

C:\Users\PC\AppData\Local\Temp\ipykernel_9628\1263437766.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_streamlit = pd.read_csv("data/Conversion_rate_user_info.csv")

In [20]:
df_quicksight

,UserId,EventType,EventType.1,EventDateTime,EventType_soft,EventType_soft.1,EventDateTime_soft,DateDifference_soft,FundingIn2weeks_soft,EventType_hot,...,DateDifference_portafolioC,FundingIn2weeks_portafolioC,EventType_identityV,EventDateTime_identityV,DateDifference_identityV,FundingIn2weeks_identityV,EventType_accountIF,EventDateTime_accountIF,DateDifference_accountIF,FundingIn2weeks_accountIF
0,1112158,SOFT_LEAD,SOFT_LEAD,2023-01-01T00:32:48+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 00:32:48.960000+00:00,0,1,NaN,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
1,1112159,SOFT_LEAD,SOFT_LEAD,2023-01-01T00:52:35+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 00:52:35.264000+00:00,0,1,HOT_LEAD,...,0.0,1,IDENTITY_VERIFIED,2023-01-08 15:10:20.931000+00:00,7.0,1,NaN,NaN,NaN,0
2,1112160,SOFT_LEAD,SOFT_LEAD,2023-01-01T01:07:16+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 01:07:16.701000+00:00,0,1,HOT_LEAD,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
3,1112161,SOFT_LEAD,SOFT_LEAD,2023-01-01T01:19:29+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 01:19:29.752000+00:00,0,1,HOT_LEAD,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
4,1112162,SOFT_LEAD,SOFT_LEAD,2023-01-01T01:19:39+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 01:19:39.792000+00:00,0,1,HOT_LEAD,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51542,1163797,SOFT_LEAD,SOFT_LEAD,2023-12-14T07:36:09+0000,SOFT_LEAD,SOFT_LEAD,2023-12-14 07:36:09.167000+00:00,0,1,HOT_LEAD,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
51543,1163798,SOFT_LEAD,SOFT_LEAD,2023-12-14T07:36:48+0000,SOFT_LEAD,SOFT_LEAD,2023-12-14 07:36:48.228000+00:00,0,1,HOT_LEAD,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
51544,1163799,SOFT_LEAD,SOFT_LEAD,2023-12-14T07:43:23+0000,SOFT_LEAD,SOFT_LEAD,2023-12-14 07:43:23.828000+00:00,0,1,HOT_LEAD,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
51545,1163800,SOFT_LEAD,SOFT_LEAD,2023-12-14T07:54:46+0000,SOFT_LEAD,SOFT_LEAD,2023-12-14 07:54:46.673000+00:00,0,1,HOT_LEAD,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
51546,1163801,SOFT_LEAD,SOFT_LEAD,2023-12-14T08:47:02+0000,SOFT_LEAD,SOFT_LEAD,2023-12-14 08:47:02.788000+00:00,0,1,HOT_LEAD,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0

In [21]:
df_streamlit

,UserId,EventType,EventType.1,EventDateTime,Platform,User.M.Age.N,User.M.Income.N,EventType_soft,EventType_soft.1,EventDateTime_soft,...,DateDifference_portafolioC,FundingIn2weeks_portafolioC,EventType_identityV,EventDateTime_identityV,DateDifference_identityV,FundingIn2weeks_identityV,EventType_accountIF,EventDateTime_accountIF,DateDifference_accountIF,FundingIn2weeks_accountIF
0,1112158,SOFT_LEAD,SOFT_LEAD,2023-01-01T00:32:48+0000,NaN,NaN,NaN,SOFT_LEAD,SOFT_LEAD,2023-01-01 00:32:48.960000+00:00,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
1,1112159,SOFT_LEAD,SOFT_LEAD,2023-01-01T00:52:35+0000,NaN,27.0,12500.0,SOFT_LEAD,SOFT_LEAD,2023-01-01 00:52:35.264000+00:00,...,0.0,1,IDENTITY_VERIFIED,2023-01-08 15:10:20.931000+00:00,7.0,1,NaN,NaN,NaN,0
2,1112160,SOFT_LEAD,SOFT_LEAD,2023-01-01T01:07:16+0000,NaN,NaN,NaN,SOFT_LEAD,SOFT_LEAD,2023-01-01 01:07:16.701000+00:00,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
3,1112161,SOFT_LEAD,SOFT_LEAD,2023-01-01T01:19:29+0000,NaN,NaN,NaN,SOFT_LEAD,SOFT_LEAD,2023-01-01 01:19:29.752000+00:00,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
4,1112162,SOFT_LEAD,SOFT_LEAD,2023-01-01T01:19:39+0000,NaN,NaN,NaN,SOFT_LEAD,SOFT_LEAD,2023-01-01 01:19:39.792000+00:00,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51753,1164008,SOFT_LEAD,SOFT_LEAD,2023-12-15T07:03:42+0000,iOS,26.0,12500.0,SOFT_LEAD,SOFT_LEAD,2023-12-15 07:03:42.681000+00:00,...,0.0,1,NaN,NaN,NaN,0,NaN,NaN,NaN,0
51754,1164009,SOFT_LEAD,SOFT_LEAD,2023-12-15T07:26:43+0000,iOS,24.0,NaN,SOFT_LEAD,SOFT_LEAD,2023-12-15 07:26:43.734000+00:00,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
51755,1164010,SOFT_LEAD,SOFT_LEAD,2023-12-15T08:13:10+0000,iOS,NaN,NaN,SOFT_LEAD,SOFT_LEAD,2023-12-15 08:13:10.728000+00:00,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
51756,1164011,SOFT_LEAD,SOFT_LEAD,2023-12-15T08:31:43+0000,iOS,NaN,NaN,SOFT_LEAD,SOFT_LEAD,2023-12-15 08:31:43.301000+00:00,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
51757,1164012,SOFT_LEAD,SOFT_LEAD,2023-12-15T08:50:00+0000,iOS,NaN,NaN,SOFT_LEAD,SOFT_LEAD,2023-12-15 08:50:00.193000+00:00,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0

In [22]:
df_streamlit.columns

Index(['UserId', 'EventType', 'EventType.1', 'EventDateTime', 'Platform',
       'User.M.Age.N', 'User.M.Income.N', 'EventType_soft', 'EventType_soft.1',
       'EventDateTime_soft', 'DateDifference_soft', 'FundingIn2weeks_soft',
       'EventType_hot', 'EventDateTime_hot', 'DateDifference_hot',
       'FundingIn2weeks_hot', 'EventType_mobile', 'EventDateTime_mobile',
       'DateDifference_mobile', 'FundingIn2weeks_mobile', 'EventType_emma',
       'EventDateTime_emma', 'DateDifference_emma', 'FundingIn2weeks_emma',
       'EventType_identity', 'EventDateTime_identity',
       'DateDifference_identity', 'FundingIn2weeks_identity',
       'EventType_address', 'EventDateTime_address', 'DateDifference_address',
       'FundingIn2weeks_address', 'EventType_disclosures',
       'EventDateTime_disclosures', 'DateDifference_disclosures',
       'FundingIn2weeks_disclosures', 'EventType_agreements',
       'EventDateTime_agreements', 'DateDifference_agreements',
       'FundingIn2weeks_agreements', 'EventType_financial',
       'EventDateTime_financial', 'DateDifference_financial',
       'FundingIn2weeks_financial', 'EventType_portafolioS',
       'EventDateTime_portafolioS', 'DateDifference_portafolioS',
       'FundingIn2weeks_portafolioS', 'EventType_portafolioC',
       'EventDateTime_portafolioC', 'DateDifference_portafolioC',
       'FundingIn2weeks_portafolioC', 'EventType_identityV',
       'EventDateTime_identityV', 'DateDifference_identityV',
       'FundingIn2weeks_identityV', 'EventType_accountIF',
       'EventDateTime_accountIF', 'DateDifference_accountIF',
       'FundingIn2weeks_accountIF'],
      dtype='object')

# Noviembre

## Using concatenated of quicksilver

In [23]:
prueba_qs = df_quicksight [ df_quicksight["EventDateTime_soft"].dt.month == 11]

prueba_qs = prueba_qs.filter(like="accountIF")

In [24]:
prueba_qs

,EventType_accountIF,EventDateTime_accountIF,DateDifference_accountIF,FundingIn2weeks_accountIF
40811,NaN,NaN,NaN,0
40812,NaN,NaN,NaN,0
40813,NaN,NaN,NaN,0
40814,NaN,NaN,NaN,0
40815,NaN,NaN,NaN,0
...,...,...,...,...
48374,NaN,NaN,NaN,0
48375,NaN,NaN,NaN,0
48376,NaN,NaN,NaN,0
48377,NaN,NaN,NaN,0
48378,NaN,NaN,NaN,0

In [46]:
len( prueba_qs[ prueba_qs["FundingIn2weeks_accountIF"] ==1  ].index)

269

In [47]:
len(prueba_qs.index)

7568

In [25]:
len( prueba_qs[ prueba_qs["FundingIn2weeks_accountIF"] ==1  ].index) / len(prueba_qs.index)

0.035544397463002114

## Using Conversion_rate_user_info

In [26]:
prueba_st = df_streamlit [ df_streamlit["EventDateTime_soft"].dt.month == 11]
prueba_st

,UserId,EventType,EventType.1,EventDateTime,Platform,User.M.Age.N,User.M.Income.N,EventType_soft,EventType_soft.1,EventDateTime_soft,...,DateDifference_portafolioC,FundingIn2weeks_portafolioC,EventType_identityV,EventDateTime_identityV,DateDifference_identityV,FundingIn2weeks_identityV,EventType_accountIF,EventDateTime_accountIF,DateDifference_accountIF,FundingIn2weeks_accountIF
40811,1153053,SOFT_LEAD,SOFT_LEAD,2023-11-01T00:03:38+0000,NaN,NaN,NaN,SOFT_LEAD,SOFT_LEAD,2023-11-01 00:03:38.118000+00:00,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
40812,1153054,SOFT_LEAD,SOFT_LEAD,2023-11-01T00:15:15+0000,Android,NaN,NaN,SOFT_LEAD,SOFT_LEAD,2023-11-01 00:15:15.390000+00:00,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
40813,1153055,SOFT_LEAD,SOFT_LEAD,2023-11-01T00:21:27+0000,Android,NaN,NaN,SOFT_LEAD,SOFT_LEAD,2023-11-01 00:21:27.662000+00:00,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
40814,1153056,SOFT_LEAD,SOFT_LEAD,2023-11-01T00:31:25+0000,iOS,NaN,NaN,SOFT_LEAD,SOFT_LEAD,2023-11-01 00:31:25.592000+00:00,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
40815,1153057,SOFT_LEAD,SOFT_LEAD,2023-11-01T00:52:11+0000,iOS,NaN,NaN,SOFT_LEAD,SOFT_LEAD,2023-11-01 00:52:11.193000+00:00,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48374,1160624,SOFT_LEAD,SOFT_LEAD,2023-11-30T23:36:19+0000,iOS,NaN,NaN,SOFT_LEAD,SOFT_LEAD,2023-11-30 23:36:19.449000+00:00,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
48375,1160625,SOFT_LEAD,SOFT_LEAD,2023-11-30T23:38:44+0000,iOS,21.0,12500.0,SOFT_LEAD,SOFT_LEAD,2023-11-30 23:38:44.669000+00:00,...,0.0,1,IDENTITY_VERIFIED,2023-11-30 23:52:14.427000+00:00,0.0,1,ACCOUNT_COMPLETE,2023-12-01 06:31:10.845000+00:00,0.0,1
48376,1160626,SOFT_LEAD,SOFT_LEAD,2023-11-30T23:46:46+0000,iOS,NaN,NaN,SOFT_LEAD,SOFT_LEAD,2023-11-30 23:46:46.203000+00:00,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
48377,1160627,SOFT_LEAD,SOFT_LEAD,2023-11-30T23:48:04+0000,Android,32.0,37500.0,SOFT_LEAD,SOFT_LEAD,2023-11-30 23:48:04.739000+00:00,...,0.0,1,IDENTITY_VERIFIED,2023-12-01 00:00:33.931000+00:00,0.0,1,NaN,NaN,NaN,0
48378,1160628,SOFT_LEAD,SOFT_LEAD,2023-11-30T23:58:06+0000,iOS,NaN,NaN,SOFT_LEAD,SOFT_LEAD,2023-11-30 23:58:06.385000+00:00,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0

In [45]:
len( prueba_st[ prueba_st["FundingIn2weeks_accountIF"] ==1  ].index)

634

In [48]:
len(prueba_st.index)

7568

In [27]:
# registros positvos de FundingIn2weeks_accountIF / total del df en noviembre
len( prueba_st[ prueba_st["FundingIn2weeks_accountIF"] ==1  ].index) / len(prueba_st.index)

0.08377378435517971

In [28]:
result = df_streamlit.groupby([df_streamlit['EventDateTime_soft'].dt.to_period("M")]).agg(
    total_rows=pd.NamedAgg(column='EventDateTime_soft', aggfunc='size'),
    count_values_positives=pd.NamedAgg(column='FundingIn2weeks_accountIF', aggfunc=lambda x: sum(x == 1))
).reset_index()

result["ConversionRate"] = ( result["count_values_positives"] / result["total_rows"] ) * 100

result

C:\Users\PC\AppData\Local\Temp\ipykernel_9628\2503696239.py:1: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  result = df_streamlit.groupby([df_streamlit['EventDateTime_soft'].dt.to_period("M")]).agg(

   EventDateTime_soft  total_rows  count_values_positives  ConversionRate
0             2023-01        3922                     539       13.742988
1             2023-02        4303                     559       12.990937
2             2023-03        5027                     653       12.989855
3             2023-04        3578                     469       13.107881
4             2023-05        4003                     412       10.292281
5             2023-06        3005                     375       12.479201
6             2023-07        4541                     597       13.146884
7             2023-08        3610                     498       13.795014
8             2023-09        3168                     485       15.309343
9             2023-10        5654                     471        8.330386
10            2023-11        7568                     634        8.377378
11            2023-12        3379                     336        9.943770

In [29]:
result["EventType"] = [df_streamlit.dropna()["EventType_accountIF"].unique()[0]] * len(result.index)
result

,EventDateTime_soft,total_rows,count_values_positives,ConversionRate,EventType
0,2023-01,3922,539,13.742988,ACCOUNT_COMPLETE
1,2023-02,4303,559,12.990937,ACCOUNT_COMPLETE
2,2023-03,5027,653,12.989855,ACCOUNT_COMPLETE
3,2023-04,3578,469,13.107881,ACCOUNT_COMPLETE
4,2023-05,4003,412,10.292281,ACCOUNT_COMPLETE
5,2023-06,3005,375,12.479201,ACCOUNT_COMPLETE
6,2023-07,4541,597,13.146884,ACCOUNT_COMPLETE
7,2023-08,3610,498,13.795014,ACCOUNT_COMPLETE
8,2023-09,3168,485,15.309343,ACCOUNT_COMPLETE
9,2023-10,5654,471,8.330386,ACCOUNT_COMPLETE
10,2023-11,7568,634,8.377378,ACCOUNT_COMPLETE
11,2023-12,3379,336,9.943770,ACCOUNT_COMPLETE

## Using Conversion_rate_user_info, without na in platform, age and income

In [30]:
prueba_st_without_na = prueba_st.dropna(subset=["Platform", "User.M.Age.N", "User.M.Income.N"], how='any')

In [31]:
prueba_st_without_na

,UserId,EventType,EventType.1,EventDateTime,Platform,User.M.Age.N,User.M.Income.N,EventType_soft,EventType_soft.1,EventDateTime_soft,...,DateDifference_portafolioC,FundingIn2weeks_portafolioC,EventType_identityV,EventDateTime_identityV,DateDifference_identityV,FundingIn2weeks_identityV,EventType_accountIF,EventDateTime_accountIF,DateDifference_accountIF,FundingIn2weeks_accountIF
40823,1153065,SOFT_LEAD,SOFT_LEAD,2023-11-01T01:45:45+0000,iOS,44.0,62500.0,SOFT_LEAD,SOFT_LEAD,2023-11-01 01:45:45.711000+00:00,...,0.0,1,IDENTITY_VERIFIED,2023-11-01 01:54:44.618000+00:00,0.0,1,ACCOUNT_COMPLETE,2023-11-01 08:30:47.486000+00:00,0.0,1
40827,1153069,SOFT_LEAD,SOFT_LEAD,2023-11-01T02:13:35+0000,iOS,22.0,62500.0,SOFT_LEAD,SOFT_LEAD,2023-11-01 02:13:35.589000+00:00,...,0.0,1,IDENTITY_VERIFIED,2023-11-01 02:27:02.550000+00:00,0.0,1,ACCOUNT_COMPLETE,2023-11-02 18:00:58.771000+00:00,1.0,1
40836,1153078,SOFT_LEAD,SOFT_LEAD,2023-11-01T03:04:56+0000,iOS,20.0,12500.0,SOFT_LEAD,SOFT_LEAD,2023-11-01 03:04:56.985000+00:00,...,0.0,1,NaN,NaN,NaN,0,NaN,NaN,NaN,0
40839,1153081,SOFT_LEAD,SOFT_LEAD,2023-11-01T03:16:48+0000,Android,42.0,12500.0,SOFT_LEAD,SOFT_LEAD,2023-11-01 03:16:48.773000+00:00,...,0.0,1,IDENTITY_VERIFIED,2023-11-01 15:07:09.643000+00:00,0.0,1,NaN,NaN,NaN,0
40846,1153088,SOFT_LEAD,SOFT_LEAD,2023-11-01T03:49:23+0000,Android,50.0,37500.0,SOFT_LEAD,SOFT_LEAD,2023-11-01 03:49:23.994000+00:00,...,1.0,1,NaN,NaN,NaN,0,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48361,1160611,SOFT_LEAD,SOFT_LEAD,2023-11-30T21:05:42+0000,iOS,45.0,37500.0,SOFT_LEAD,SOFT_LEAD,2023-11-30 21:05:42.663000+00:00,...,0.0,1,IDENTITY_VERIFIED,2023-11-30 21:21:59.718000+00:00,0.0,1,NaN,NaN,NaN,0
48362,1160612,SOFT_LEAD,SOFT_LEAD,2023-11-30T21:18:51+0000,iOS,60.0,96000.0,SOFT_LEAD,SOFT_LEAD,2023-11-30 21:18:51.047000+00:00,...,0.0,1,IDENTITY_VERIFIED,2023-11-30 22:35:24.824000+00:00,0.0,1,NaN,NaN,NaN,0
48363,1160613,SOFT_LEAD,SOFT_LEAD,2023-11-30T21:20:28+0000,iOS,18.0,12500.0,SOFT_LEAD,SOFT_LEAD,2023-11-30 21:20:28.404000+00:00,...,0.0,1,NaN,NaN,NaN,0,NaN,NaN,NaN,0
48375,1160625,SOFT_LEAD,SOFT_LEAD,2023-11-30T23:38:44+0000,iOS,21.0,12500.0,SOFT_LEAD,SOFT_LEAD,2023-11-30 23:38:44.669000+00:00,...,0.0,1,IDENTITY_VERIFIED,2023-11-30 23:52:14.427000+00:00,0.0,1,ACCOUNT_COMPLETE,2023-12-01 06:31:10.845000+00:00,0.0,1
48377,1160627,SOFT_LEAD,SOFT_LEAD,2023-11-30T23:48:04+0000,Android,32.0,37500.0,SOFT_LEAD,SOFT_LEAD,2023-11-30 23:48:04.739000+00:00,...,0.0,1,IDENTITY_VERIFIED,2023-12-01 00:00:33.931000+00:00,0.0,1,NaN,NaN,NaN,0

In [32]:
len( prueba_st_without_na[ prueba_st_without_na["FundingIn2weeks_accountIF"] ==1  ].index) / len(prueba_st_without_na.index)

0.32752808988764043

In [33]:
df_streamlit_with_na = df_streamlit.dropna(subset=["Platform", "User.M.Age.N", "User.M.Income.N"], how='any')

In [38]:
result = df_streamlit_with_na.groupby([df_streamlit_with_na['EventDateTime_soft'].dt.to_period("M")]).agg(
    total_rows=pd.NamedAgg(column='EventDateTime_soft', aggfunc='size'),
    count_values_positives=pd.NamedAgg(column='FundingIn2weeks_accountIF', aggfunc=lambda x: sum(x == 1))
).reset_index()

result["ConversionRate"] = ( result["count_values_positives"] / result["total_rows"] ) * 100

result

C:\Users\PC\AppData\Local\Temp\ipykernel_9628\252318412.py:1: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  result = df_streamlit_with_na.groupby([df_streamlit_with_na['EventDateTime_soft'].dt.to_period("M")]).agg(

  EventDateTime_soft  total_rows  count_values_positives  ConversionRate
0            2023-06         870                     307       35.287356
1            2023-07        1478                     554       37.483085
2            2023-08        1099                     460       41.856233
3            2023-09        1036                     451       43.532819
4            2023-10        1324                     423       31.948640
5            2023-11        1780                     583       32.752809
6            2023-12         692                     275       39.739884

In [35]:
result["EventType"] = [prueba_st_without_na.dropna()["EventType_accountIF"].unique()[0]] * len(result.index)
result

,EventDateTime_soft,total_rows,count_values_positives,ConversionRate,EventType
0,2023-06,870,307,35.287356,ACCOUNT_COMPLETE
1,2023-07,1478,554,37.483085,ACCOUNT_COMPLETE
2,2023-08,1099,460,41.856233,ACCOUNT_COMPLETE
3,2023-09,1036,451,43.532819,ACCOUNT_COMPLETE
4,2023-10,1324,423,31.948640,ACCOUNT_COMPLETE
5,2023-11,1780,583,32.752809,ACCOUNT_COMPLETE
6,2023-12,692,275,39.739884,ACCOUNT_COMPLETE

In [41]:
df_filter =  df_streamlit[df_streamlit['User.M.Age.N'].between( 17, 69)]
df_filter =  df_filter[df_filter['User.M.Income.N'].between( 12500.00, 184000.00)]
df_filter =  df_filter[df_filter['Platform'] == "iOS"]

In [42]:
result = df_filter.groupby([df_filter['EventDateTime_soft'].dt.to_period("M")]).agg(
    total_rows=pd.NamedAgg(column='EventDateTime_soft', aggfunc='size'),
    count_values_positives=pd.NamedAgg(column='FundingIn2weeks_accountIF', aggfunc=lambda x: sum(x == 1))
).reset_index()

result["ConversionRate"] = ( result["count_values_positives"] / result["total_rows"] ) * 100

result

C:\Users\PC\AppData\Local\Temp\ipykernel_9628\3279348576.py:1: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  result = df_filter.groupby([df_filter['EventDateTime_soft'].dt.to_period("M")]).agg(

  EventDateTime_soft  total_rows  count_values_positives  ConversionRate
0            2023-06         824                     281       34.101942
1            2023-07        1400                     506       36.142857
2            2023-08        1032                     424       41.085271
3            2023-09         975                     414       42.461538
4            2023-10         779                     280       35.943517
5            2023-11        1124                     436       38.790036
6            2023-12         565                     225       39.823009