In [11]:
import pandas as pd
import numpy as np

In [12]:
df_quicksight = pd.read_csv("data/concatenated_df_2.csv")
df_streamlit = pd.read_csv("data/users_daily_2023_12_18.csv")


#df_quicksight[ 'EventDateTime_soft' ] = pd.to_datetime(df_quicksight[ 'EventDateTime_soft'], format="%Y-%m-%dT%H:%M:%S%z")

df_quicksight['EventDateTime_soft'] = pd.to_datetime(df_quicksight['EventDateTime_soft'], format='ISO8601')

In [13]:
df_quicksight

,UserId,EventType,EventType.1,EventDateTime,EventType_soft,EventType_soft.1,EventDateTime_soft,DateDifference_soft,FundingIn2weeks_soft,EventType_hot,...,DateDifference_bankC,FundingIn2weeks_bankC,EventType_bankA,EventDateTime_bankA,DateDifference_bankA,FundingIn2weeks_bankA,EventType_accountIF,EventDateTime_accountIF,DateDifference_accountIF,FundingIn2weeks_accountIF
0,1112158,SOFT_LEAD,SOFT_LEAD,2023-01-01T00:32:48+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 00:32:48.960000+00:00,0,1,NaN,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
1,1112159,SOFT_LEAD,SOFT_LEAD,2023-01-01T00:52:35+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 00:52:35.264000+00:00,0,1,HOT_LEAD,...,7.0,1,NaN,NaN,NaN,0,NaN,NaN,NaN,0
2,1112160,SOFT_LEAD,SOFT_LEAD,2023-01-01T01:07:16+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 01:07:16.701000+00:00,0,1,HOT_LEAD,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
3,1112161,SOFT_LEAD,SOFT_LEAD,2023-01-01T01:19:29+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 01:19:29.752000+00:00,0,1,HOT_LEAD,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
4,1112162,SOFT_LEAD,SOFT_LEAD,2023-01-01T01:19:39+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 01:19:39.792000+00:00,0,1,HOT_LEAD,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55103,1167360,SOFT_LEAD,SOFT_LEAD,2023-12-27T07:18:34+0000,SOFT_LEAD,SOFT_LEAD,2023-12-27 07:18:34.227000+00:00,0,1,HOT_LEAD,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
55104,1167361,SOFT_LEAD,SOFT_LEAD,2023-12-27T07:37:01+0000,SOFT_LEAD,SOFT_LEAD,2023-12-27 07:37:01.167000+00:00,0,1,HOT_LEAD,...,0.0,1,NaN,NaN,NaN,0,NaN,NaN,NaN,0
55105,1167362,SOFT_LEAD,SOFT_LEAD,2023-12-27T07:37:20+0000,SOFT_LEAD,SOFT_LEAD,2023-12-27 07:37:20.265000+00:00,0,1,HOT_LEAD,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
55106,1167363,SOFT_LEAD,SOFT_LEAD,2023-12-27T07:46:59+0000,SOFT_LEAD,SOFT_LEAD,2023-12-27 07:46:59.821000+00:00,0,1,HOT_LEAD,...,0.0,1,NaN,NaN,NaN,0,NaN,NaN,NaN,0
55107,1167364,SOFT_LEAD,SOFT_LEAD,2023-12-27T07:52:29+0000,SOFT_LEAD,SOFT_LEAD,2023-12-27 07:52:29.133000+00:00,0,1,HOT_LEAD,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0

In [14]:
df_quicksight.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55108 entries, 0 to 55107
Data columns (total 73 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   UserId                       55108 non-null  int64
 1   EventType                    55108 non-null  object
 2   EventType.1                  55108 non-null  object
 3   EventDateTime                55108 non-null  object
 4   EventType_soft               55108 non-null  object
 5   EventType_soft.1             55108 non-null  object
 6   EventDateTime_soft           55108 non-null  datetime64[ns, UTC]
 7   DateDifference_soft          55108 non-null  int64
 8   FundingIn2weeks_soft         55108 non-null  int64
 9   EventType_hot                48414 non-null  object
 10  EventDateTime_hot            48414 non-null  object
 11  DateDifference_hot           48414 non-null  float64
 12  FundingIn2weeks_hot          55108 non-null  int64
 13  EventType_mobile             32415 non-null  object
 14  EventDateTime_mobile         32415 non-null  object
 15  DateDifference_mobile        32415 non-null  float64
 16  FundingIn2weeks_mobile       55108 non-null  int64
 17  EventType_emma               36536 non-null  object
 18  EventDateTime_emma           36536 non-null  object
 19  DateDifference_emma          36536 non-null  float64
 20  FundingIn2weeks_emma         55108 non-null  int64
 21  EventType_identity           24044 non-null  object
 22  EventDateTime_identity       24044 non-null  object
 23  DateDifference_identity      24044 non-null  float64
 24  FundingIn2weeks_identity     55108 non-null  int64
 25  EventType_address            21957 non-null  object
 26  EventDateTime_address        21957 non-null  object
 27  DateDifference_address       21957 non-null  float64
 28  FundingIn2weeks_address      55108 non-null  int64
 29  EventType_disclosures        21602 non-null  object
 30  EventDateTime_disclosures    21602 non-null  object
 31  DateDifference_disclosures   21602 non-null  float64
 32  FundingIn2weeks_disclosures  55108 non-null  int64
 33  EventType_agreements         17427 non-null  object
 34  EventDateTime_agreements     17427 non-null  object
 35  DateDifference_agreements    17427 non-null  float64
 36  FundingIn2weeks_agreements   55108 non-null  int64
 37  EventType_financial          19298 non-null  object
 38  EventDateTime_financial      19298 non-null  object
 39  DateDifference_financial     19298 non-null  float64
 40  FundingIn2weeks_financial    55108 non-null  int64
 41  EventType_portafolioS        17070 non-null  object
 42  EventDateTime_portafolioS    17070 non-null  object
 43  DateDifference_portafolioS   17070 non-null  float64
 44  FundingIn2weeks_portafolioS  55108 non-null  int64
 45  EventType_portafolioC        17002 non-null  object
 46  EventDateTime_portafolioC    17002 non-null  object
 47  DateDifference_portafolioC   17002 non-null  float64
 48  FundingIn2weeks_portafolioC  55108 non-null  int64
 49  EventType_identityV          11972 non-null  object
 50  EventDateTime_identityV      11972 non-null  object
 51  DateDifference_identityV     11972 non-null  float64
 52  FundingIn2weeks_identityV    55108 non-null  int64
 53  EventType_accountC           7118 non-null   object
 54  EventDateTime_accountC       7118 non-null   object
 55  DateDifference_accountC      7118 non-null   float64
 56  FundingIn2weeks_accountC     55108 non-null  int64
 57  EventType_accountR           6159 non-null   object
 58  EventDateTime_accountR       6159 non-null   object
 59  DateDifference_accountR      6159 non-null   float64
 60  FundingIn2weeks_accountR     55108 non-null  int64
 61  EventType_bankC              7007 non-null   object
 62  EventDateTime_bankC          7007 non-null   object
 63  DateDifference_bankC         7007 non-null   float64
 64  FundingIn2weeks_bankC        55108 non-null  int64
 65  EventType_bankA              4676 non-null   object
 66  EventDateTime_bankA          4676 non-null   object
 67  DateDifference_bankA         4676 non-null   float64
 68  FundingIn2weeks_bankA        55108 non-null  int64
 69  EventType_accountIF          3984 non-null   object
 70  EventDateTime_accountIF      3984 non-null   object
 71  DateDifference_accountIF     3984 non-null   float64
 72  FundingIn2weeks_accountIF    55108 non-null  int64
dtypes: datetime64[ns, UTC](1), float64(16), int64(19), object(37)
memory usage: 30.7+ MB

In [15]:
df_streamlit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 695450 entries, 0 to 695449
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   dateOfBirth     412427 non-null  object
 1   maritalStatus   412236 non-null  object
 2   income          317319 non-null  float64
 3   language        695450 non-null  object
 4   devicePlatform  638923 non-null  object
 5   userId          695450 non-null  int64
dtypes: float64(1), int64(1), object(4)
memory usage: 31.8+ MB

In [16]:
csv_merge = pd.merge(df_quicksight, df_streamlit, how="left", left_on= "UserId", right_on="userId")
csv_merge

,UserId,EventType,EventType.1,EventDateTime,EventType_soft,EventType_soft.1,EventDateTime_soft,DateDifference_soft,FundingIn2weeks_soft,EventType_hot,...,EventType_accountIF,EventDateTime_accountIF,DateDifference_accountIF,FundingIn2weeks_accountIF,dateOfBirth,maritalStatus,income,language,devicePlatform,userId
0,1112158,SOFT_LEAD,SOFT_LEAD,2023-01-01T00:32:48+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 00:32:48.960000+00:00,0,1,NaN,...,NaN,NaN,NaN,0,NaN,NaN,NaN,en,iOS,1112158.0
1,1112159,SOFT_LEAD,SOFT_LEAD,2023-01-01T00:52:35+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 00:52:35.264000+00:00,0,1,HOT_LEAD,...,NaN,NaN,NaN,0,1995-11-15T17:00:00-0700,SINGLE,12500.0,es,iOS,1112159.0
2,1112160,SOFT_LEAD,SOFT_LEAD,2023-01-01T01:07:16+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 01:07:16.701000+00:00,0,1,HOT_LEAD,...,NaN,NaN,NaN,0,NaN,NaN,NaN,es,iOS,1112160.0
3,1112161,SOFT_LEAD,SOFT_LEAD,2023-01-01T01:19:29+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 01:19:29.752000+00:00,0,1,HOT_LEAD,...,NaN,NaN,NaN,0,NaN,NaN,NaN,es,iOS,1112161.0
4,1112162,SOFT_LEAD,SOFT_LEAD,2023-01-01T01:19:39+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 01:19:39.792000+00:00,0,1,HOT_LEAD,...,NaN,NaN,NaN,0,NaN,NaN,NaN,es,iOS,1112162.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55103,1167360,SOFT_LEAD,SOFT_LEAD,2023-12-27T07:18:34+0000,SOFT_LEAD,SOFT_LEAD,2023-12-27 07:18:34.227000+00:00,0,1,HOT_LEAD,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
55104,1167361,SOFT_LEAD,SOFT_LEAD,2023-12-27T07:37:01+0000,SOFT_LEAD,SOFT_LEAD,2023-12-27 07:37:01.167000+00:00,0,1,HOT_LEAD,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
55105,1167362,SOFT_LEAD,SOFT_LEAD,2023-12-27T07:37:20+0000,SOFT_LEAD,SOFT_LEAD,2023-12-27 07:37:20.265000+00:00,0,1,HOT_LEAD,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
55106,1167363,SOFT_LEAD,SOFT_LEAD,2023-12-27T07:46:59+0000,SOFT_LEAD,SOFT_LEAD,2023-12-27 07:46:59.821000+00:00,0,1,HOT_LEAD,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
55107,1167364,SOFT_LEAD,SOFT_LEAD,2023-12-27T07:52:29+0000,SOFT_LEAD,SOFT_LEAD,2023-12-27 07:52:29.133000+00:00,0,1,HOT_LEAD,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
csv_merge['dateOfBirth'] = pd.to_datetime(csv_merge['dateOfBirth'], utc=True)
current_date = pd.to_datetime('today', utc=True)
csv_merge['age'] = np.floor((current_date - csv_merge['dateOfBirth']) / np.timedelta64(1, 'Y'))

In [18]:
csv_merge.to_csv("data/merge_data_v2.csv", index=False)

In [19]:
csv_merge

,UserId,EventType,EventType.1,EventDateTime,EventType_soft,EventType_soft.1,EventDateTime_soft,DateDifference_soft,FundingIn2weeks_soft,EventType_hot,...,EventDateTime_accountIF,DateDifference_accountIF,FundingIn2weeks_accountIF,dateOfBirth,maritalStatus,income,language,devicePlatform,userId,age
0,1112158,SOFT_LEAD,SOFT_LEAD,2023-01-01T00:32:48+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 00:32:48.960000+00:00,0,1,NaN,...,NaN,NaN,0,NaT,NaN,NaN,en,iOS,1112158.0,NaN
1,1112159,SOFT_LEAD,SOFT_LEAD,2023-01-01T00:52:35+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 00:52:35.264000+00:00,0,1,HOT_LEAD,...,NaN,NaN,0,1995-11-16 00:00:00+00:00,SINGLE,12500.0,es,iOS,1112159.0,28.0
2,1112160,SOFT_LEAD,SOFT_LEAD,2023-01-01T01:07:16+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 01:07:16.701000+00:00,0,1,HOT_LEAD,...,NaN,NaN,0,NaT,NaN,NaN,es,iOS,1112160.0,NaN
3,1112161,SOFT_LEAD,SOFT_LEAD,2023-01-01T01:19:29+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 01:19:29.752000+00:00,0,1,HOT_LEAD,...,NaN,NaN,0,NaT,NaN,NaN,es,iOS,1112161.0,NaN
4,1112162,SOFT_LEAD,SOFT_LEAD,2023-01-01T01:19:39+0000,SOFT_LEAD,SOFT_LEAD,2023-01-01 01:19:39.792000+00:00,0,1,HOT_LEAD,...,NaN,NaN,0,NaT,NaN,NaN,es,iOS,1112162.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55103,1167360,SOFT_LEAD,SOFT_LEAD,2023-12-27T07:18:34+0000,SOFT_LEAD,SOFT_LEAD,2023-12-27 07:18:34.227000+00:00,0,1,HOT_LEAD,...,NaN,NaN,0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
55104,1167361,SOFT_LEAD,SOFT_LEAD,2023-12-27T07:37:01+0000,SOFT_LEAD,SOFT_LEAD,2023-12-27 07:37:01.167000+00:00,0,1,HOT_LEAD,...,NaN,NaN,0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
55105,1167362,SOFT_LEAD,SOFT_LEAD,2023-12-27T07:37:20+0000,SOFT_LEAD,SOFT_LEAD,2023-12-27 07:37:20.265000+00:00,0,1,HOT_LEAD,...,NaN,NaN,0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
55106,1167363,SOFT_LEAD,SOFT_LEAD,2023-12-27T07:46:59+0000,SOFT_LEAD,SOFT_LEAD,2023-12-27 07:46:59.821000+00:00,0,1,HOT_LEAD,...,NaN,NaN,0,NaT,NaN,NaN,NaN,NaN,NaN,NaN
55107,1167364,SOFT_LEAD,SOFT_LEAD,2023-12-27T07:52:29+0000,SOFT_LEAD,SOFT_LEAD,2023-12-27 07:52:29.133000+00:00,0,1,HOT_LEAD,...,NaN,NaN,0,NaT,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
csv_merge.isna().sum()

UserId                0
EventType             0
EventType.1           0
EventDateTime         0
EventType_soft        0
                  ...
income            33693
language           2687
devicePlatform     6606
userId             2687
age               32209
Length: 80, dtype: int64